
cache: 
  paths:
    - .m2/repository

stages:
  - build
  - deploy



# Build Stage
build:
  image: maven:3.8.5-openjdk-17-slim
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar  


# Deploy Stage (example for development) 
deploy:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor \
      --context "${CI_PROJECT_DIR}" \
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile" \
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

