

cache: 
  paths:
    - .m2/repository

stages:
  - build
  - deploy


# Build Stage
build:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar  

# Deploy Stage (example for development) 
deploy:
  image: docker:stable
  services:
   - docker:dind
  stage: deploy
  environment: development
  script:
    - export DOCKER_HOST=tcp://docker:2375/
    - docker login registry.stud.idi.ntnu.no:5050 -u magngje -p glpat-f2bRq7vzUfxVNsQrM8Yz
    - docker build -t registry.stud.idi.ntnu.no:5050/idatt2106_2024_11/authservice:latest .
    - docker push registry.stud.idi.ntnu.no:5050/idatt2106_2024_11/authservice:latest
