image: maven:3.8.5-openjdk-17-slim
cache:
  paths:
    - .m2/repository

stages:
  - test
  - build
  - deploy

# Test Stage
test:
  stage: test
  script:
    - mvn test

# Build Stage
build:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: build
  image: docker:latest
  services:
    - name: docker:20-dind
      alias: docker
      command: [ "--tls=false" ]

  tags:
    - dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker login registry.stud.idi.ntnu.no:5050 -u magngje -p glpat-f2bRq7vzUfxVNsQrM8Yz
  script:
    - docker build -t registry.stud.idi.ntnu.no:5050/idatt2106_2024_11/authservice:latest .
    - docker push registry.stud.idi.ntnu.no:5050/idatt2106_2024_11/authservice:latest
