

cache: 
  paths:
    - .m2/repository

stages:
  - build
  - deploy


# Build Stage
build:
  image: maven:3.8.5-openjdk-17-slim
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar  


# Deploy Stage (example for development) 
deploy:
  image: docker:latest
  services:
    - name: docker:dind
    alias: docker
    command: ["--privileged"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  stage: deploy
  environment: development
  script:
    - docker login registry.stud.idi.ntnu.no:5050 -u magngje -p glpat-f2bRq7vzUfxVNsQrM8Yz
    - docker build -t registry.stud.idi.ntnu.no:5050/idatt2106_2024_11/authservice:latest .
    - docker push registry.stud.idi.ntnu.no:5050/idatt2106_2024_11/authservice:latest
