image: maven:3.8.5-openjdk-17-slim


cache: 
  paths:
    - .m2/repository

stages:
  - test
  - security
  - build
  - deploy

# Test Stage
test:
  stage: test
  script:
    - mvn test


# Security Stage
dependency-check:
  stage: security
  image: owasp/dependency-check 
  script:
    - owasp-dependency-check --project "AuthService"  
# Build Stage
build:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.jar  

# Deploy Stage (example for development) 
deploy:
  stage: deploy
  environment: development
  script:
    - docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_P
    - docker build -t $DOCKER_REGISTRY/$AUTH_IMAGE_NAME:latest .
    - docker push $DOCKER_REGISTRY/$AUTH_IMAGE_NAME:latest
